# ─────────────────────────────────────────────
# T E R M I N A L
# Thank you for using my theme!
# This is just a simple hobby project, something to tinker with in my down time.
# If you find issues / want features, let me know on the Repo and I'll resolve when I have free time.
# - Allan
# ─────────────────────────────────────────────


# If enabled, the 'fake crt' effect will be applied
terminal_crt_enabled: true

# Show blinking terminal cursor after blog title in header
terminal_cursor: true

# Options: 'green' | 'blue' | 'red' | 'grey' | 'amber'
terminal_color: 'green'

# Terminal Images simply applies a filter to image, this can be undesirable to blogs that are photo heavy.
# You can override specific images by using an img tag and the class 'no-filter'
terminal_images:
  enabled: true


# ─────────────────────────────────────────────
# HOME PAGE OPTIONS
# ─────────────────────────────────────────────
home_options:
  showHero: true
  heroTitle: 'Welcome To My Blog!'
  heroSubTitle: 'This is where I post about my life'
  heroButton: 
    showButton: true
    buttonTitle: 'Read More'
    buttonLink: '/about'
